version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      dev-dependencies:
        dependency-type: development
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      sst:
        patterns:
          - "sst"
          - "@pulumi/*"
      svelte:
        patterns:
          - "svelte"
          - "@sveltejs/*"
          - "svelte-*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
