# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class AppTable:
        name: str
        type: str
    class Auth:
        id: str
        type: str
    class AuthClient:
        id: str
        secret: str
        type: str
    class CreateUserProfile:
        name: str
        type: str
    class DeviceRestApi:
        type: str
        url: str
    class SfnCreateCert:
        name: str
        type: str
    class SfnCreateThing:
        name: str
        type: str
    class SfnFinalize:
        name: str
        type: str
    class SfnMarkFailed:
        name: str
        type: str
    class SfnParseStream:
        name: str
        type: str
    class SimulatorEvents:
        type: str
        url: str
    class TelemetryWriter:
        name: str
        type: str
    class Web:
        type: str
        url: str

